#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
FAILED=0

echo -e "${YELLOW}----------------------${NORMAL}"
echo -e "${YELLOW}Running eye2-swipl etc${NORMAL}"
echo -e "${YELLOW}eye2-swipl $(eye2-swipl 2>&1 | grep eye2-swipl | awk '{ print $2 }')${NORMAL}"
echo -e "${YELLOW}swipl v$(swipl --version 2>&1 | awk '{ print $3 }')${NORMAL}"
echo -e "${YELLOW}----------------------${NORMAL}"
echo ""

pad () {
    [ "$#" -gt 1 ]
    [ -n "$2" ]
    printf "%$2.${2#-}s" "$1"
}

begin=$(($(date +%s)))
for file in *.pl
do
    echo -en "$(pad "${file}" -24)"
    start=$(($(date +%s%N)/1000000))
    ../eye2-swipl "$file" > output/$file
    end=$(($(date +%s%N)/1000000))
    echo -en "${YELLOW}$(pad "`expr $end - $start` msec" 12)${NORMAL} "
    if [[ $(git diff output/${file} | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}FAILED${NORMAL}"
        ((FAILED++))
    fi
done
end=$(($(date +%s)))
echo ""

echo -e "${YELLOW}`expr $end - $begin` sec${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${FAILED} FAILED${NORMAL}"
if [[ ${FAILED} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
